theme: jekyll-theme-cayman
title: U.E.S.T.C. Missions
description: 泛成电任务索引
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
